spring:
  application:
    name: ticketbook
  server:
    port: ${SERVER_PORT}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ticketdb
      auto-index-creation: true
  config:
    import: optional:file:.env[.properties]
secret:
  key: ${SECRET_KEY}
stripe:
  api:
    key: ${STRIPE_SECRET}
    secret:  ${STRIPE_API}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.talhaatif.ticketbook.controllers

