spring:
  application:
    name: ticketbook
  server:
    port: ${SERVER_PORT}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ticketdb
      auto-index-creation: true
    cache:
      type: redis
    redis:
      host: ${REDIS_URI}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
  config:
    import: optional:file:.env[.properties]

secret:
  key: ${SECRET_KEY}
stripe:
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}
  api:
    key: ${STRIPE_SECRET}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.talhaatif.ticketbook.controllers




swagger:
  api:
    title: "🎟️ Ticket Booking API"
    version: "1.0.0"
    description: |
      Welcome to the Ticket Booking API! 🚀

      This API allows users to book and manage event tickets securely using JWT authentication.

      🔹 **Current Features:**
      - 🛠️ Admin can create, update, delete, and view events.
      - 📊 Admin can see all customer bookings.
      - 🎫 Customers can book and cancel tickets.
      - 💰 Customers can add and remove balance from their wallet.
      - 🔐 Secure login & signup with JWT authentication.
      - 🔍 Customers can filter events by page & size.
      - ⏳ Rate limiting is implemented to prevent abuse.

      **Usage:**  
      - Authenticate using the login API.
      - Click on the **Authorize** button in Swagger UI.
      - Enter the JWT token to access secured endpoints.


